config/routes.rb
WebEP::Application.routes.draw do
  devise_for :users

  resources :simulations, only: %i(index show new create) do
    member do
      get 'simulating'
      get 'check'
    end
    get 'total_site_energy_compare', on: :collection
  end

  scope controller: :home do
    get "index"
    get "help"
    get "comments"
  end

  resources :air_conditioners, as: :products_air_conditioners, controller: 'products', product_type: 'Products::AirConditioner'
  resources :lamps, as: :products_lamps, controller: 'products', product_type: 'Products::Lamp'

  resources :products do
    get 'search', on: :collection
    get 'attributes', on: :collection
  end

  root :to => 'simulations#new'

end

app/models/simulation.rb
# encoding: utf-8
# == Schema Information
#
# Table name: simulations
#
#  id                 :integer          not null, primary key
#  role               :string(255)
#  building_model     :string(255)
#  weather            :string(255)
#  room_temperature   :float
#  cop                :float
#  rate_of_decline    :integer
#  power              :string(255)
#  sun_light          :string(255)
#  people_density     :float
#  people             :integer
#  simulation_dir     :string(255)
#  user_id            :integer
#  guest_id           :integer
#  status             :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  deg                :float            default(0.0), not null
#  air_conditioner_id :integer
#

class Simulation < ActiveRecord::Base
  BUILDING_MODEL_OPTIONS = [%i(三樓 3f), %i(四樓 4f), %i(小型辦公室 small_office)]
  belongs_to :user
  belongs_to :guest
  belongs_to :air_conditioner, class_name: Products::AirConditioner
  attr_accessible :role, :building_model, :weather,
                :room_temperature, :cop, :rate_of_decline, # cooling system
                :power, :sun_light, # lighting system
                :people_density, # for business building
                :people, # for normal building
                :simulation_dir, :deg,
                :air_conditioner_id
  attr_accessor :weather_file_path, :input_file_path

  EP_BIN = Rails.root.join("lib", "EnergyPlus-7-2-0", "bin", "runenergyplus")
  BuildingModels = {
    'small_office' => Rails.root.join('lib', 'EnergyPlus-7-2-0', 'examples', 'RefBldgSmallOfficeNew2004_for_Sensitivity20130226.imf.erb'),
    '3f' => Rails.root.join('lib', 'EnergyPlus-7-2-0', 'examples', 'RRB_3F_1020731.imf.erb'),
    '4f' => Rails.root.join('lib', 'EnergyPlus-7-2-0', 'examples', '4F-3mm_0912.imf.erb'),
    'minimal' => Rails.root.join('lib', 'EnergyPlus-7-2-0', 'examples', 'Minimal.idf.erb'),
    'top' => Rails.root.join('lib', 'EnergyPlus-7-2-0', 'examples', 'Top_F_3mm_1105.imf.erb'),
    'mid' => Rails.root.join('lib', 'EnergyPlus-7-2-0', 'examples', 'Mid_F_3mm_1105.imf.erb'),
    'btn' => Rails.root.join('lib', 'EnergyPlus-7-2-0', 'examples', 'Bottom_3mm_1105.imf.erb')
  }

  after_initialize do |sim|
    sim.cop = sim.cop.to_f if sim.cop.present?
    sim.rate_of_decline = sim.rate_of_decline.to_i if sim.rate_of_decline.present?

    sim.input_file_path = BuildingModels[building_model] || BuildingModels['small_office']
    sim.weather_file_path = case weather
    when Weather::TAIPEI, Weather::KEELUNG then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'TWN_Taipei.466960_IWEC.epw')
    when Weather::HSINCHU, Weather::HSINCHUCITY, Weather::MIAOLI then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'Hsinchu2012DOE2.epw')
    when Weather::TAICHUNG then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'Taichung.epw')
    when Weather::CHIAYI, Weather::YUNLIN then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'ChiaYi_RCKU_48000_TMY3.epw')
    when Weather::TAINAN, Weather::TAINANCITY then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'TaiNan.epw')
    when Weather::KAOHSIUNG, Weather::PINGTUNG, Weather::KAOHSIUNGCITY then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'Kaohsiung_RCAY_48000_TMY3.epw')
    when Weather::TAITONG then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'TaiTong.epw')
    when Weather::HUALIAN, Weather::YILAN then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'HuaLian.epw')
    when Weather::TAOYUAN then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'TaoYuan.epw')
    when Weather::CHANGHUA, Weather::NANTOU then Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'ChangHua_TM3.epw')
    else Rails.root.join('lib', 'EnergyPlus-7-2-0', 'WeatherData', 'TWN_Taipei.466960_IWEC.epw')
    end

  end

  def run
    # OOXX.idf
    basename = File.basename(@input_file_path, '.erb')

    # public/simualtion/
    simulation_base_dir = Rails.root.join('public', 'simulation')
    FileUtils.mkdir_p simulation_base_dir
    
    # public/simulation/OOXX.idf.erbyyyymmdd/
    _simulation_dir = Dir.mktmpdir(basename, simulation_base_dir)
    # public/simulation/OOXX.idf.erbyyyymmdd/OOXX.idf
    simulation_file_path = File.join(_simulation_dir, basename)
    # render erb file
    File.write(simulation_file_path, erb_result)

    # run EnergyPlus
    `#{EP_BIN} '#{simulation_file_path}' '#{@weather_file_path}'`

    if $? == 0 # exists correctly
      Output.new File.join(_simulation_dir, 'Output')
      update_attribute :simulation_dir, _simulation_dir
    else
      raise 'Failed to execute EnergyPlus.'
    end
  end

  # Support templating of member data.
  def get_binding
    binding
  end

  def erb_result
    erb = ERB.new(File.read(@input_file_path))
    erb.result(binding)
  end

  def output
    Output.new File.join(simulation_dir, 'Output')
  end

  def building_model_text
    case building_model
    when 'small_office' then '商業類/小型辦公室'
    when '3f' then '住宅類/三樓民宅'
    when '4f' then '住宅類/四樓民宅'
    when 'top' then '住宅類/公寓頂樓'
    when 'mid' then '住宅類/公寓中間樓層'
    when 'btn' then '住宅類/公寓一樓'
    end
  end

  def room_space_text
    case building_model
    when 'small_office' then '100 坪/三房兩廳一衛'
    when '3f' then '100 坪/三房兩廳一衛'
    when 'top' then ''
    when 'mid' then ''
    when 'btn' then ''
    end
  end

  def room_space_ratial_text
    case building_model
    when 'small_office' then '廳:廳:房:房:房:衛 = 4:2:2:1.5:1:1'
    when '3f' then '廳:廳:房:房:房:衛 = 4:2:2:1.5:1:1'
    when 'top' then ''
    when 'mid' then ''
    when 'btn' then ''
    end
  end

  def weather_text
    case weather
    when Weather::TAIPEI then '台北'
    when Weather::HSINCHU then '新竹'
    when Weather::HSINCHUCITY then '新竹市'
    when Weather::TAICHUNG then '台中'
    when Weather::CHIAYI then '嘉義'
    when Weather::TAINAN then '台南'
    when Weather::KAOHSIUNG then '高雄'
    when Weather::TAITONG then '台東'
    when Weather::HUALIAN then '花蓮'
    when Weather::TAOYUAN then '桃園'
    when Weather::CHANGHUA then '彰化'
    when Weather::KEELUNG then '基隆'
    when Weather::YILAN then '宜蘭'
    when Weather::MIAOLI then '苗栗'
    when Weather::YUNLIN then '雲林'
    when Weather::NANTOU then '南投'
    when Weather::PINGTUNG then '屏東'
    when Weather::KAOHSIUNGCITY then '高雄市'
    when Weather::TAINANCITY then '台南市'
    end
  end

  def finished?
    simulation_dir.present?
  end

  def find_the_same
    Simulation.where(
      building_model: building_model,
      weather: weather,
      room_temperature: room_temperature,
      cop: cop,
      rate_of_decline: rate_of_decline,
      power: power,
      people: people,
      deg: deg
    ).where('id IS NOT ? AND simulation_dir IS NOT NULL', id).first
  end

  module Role
    NORMAL, AIR, LIGHT = %w(normal air light)
    OPTIONS = [
      ['一般使用者', NORMAL],
      ['空調業者', AIR],
      ['照明業者', LIGHT]
    ]
  end

  module Weather
    KEELUNG, TAIPEI, TAOYUAN, HSINCHU, HSINCHUCITY, MIAOLI, TAICHUNG, CHANGHUA, YUNLIN, CHIAYI, NANTOU, TAINAN, TAINANCITY, KAOHSIUNG, KAOHSIUNGCITY, PINGTUNG, TAITONG, HUALIAN, YILAN = %w(
    keelung  taipei  taoyuan  hsinchu  hsinchucity  miaoli  taichung  changhua  yunlin  chiayi  nantou  tainan  tainancity  kaohsiung  kaohsiungcity  pingtung  taitong  hualian  yilan)
    OPTIONS = [
      ['基隆', KEELUNG],
      ['台北', TAIPEI],
      ['桃園', TAOYUAN],
      ['新竹', HSINCHU],
      ['新竹市', HSINCHUCITY],
      ['苗栗', MIAOLI],
      ['台中', TAICHUNG],
      ['彰化', CHANGHUA],
      ['雲林', YUNLIN],
      ['嘉義', CHIAYI],
      ['南投', NANTOU],
      ['台南', TAINAN],
      ['台南市', TAINANCITY],
      ['高雄', KAOHSIUNG],
      ['高雄市', KAOHSIUNGCITY],
      ['屏東', PINGTUNG],
      ['台東', TAITONG],
      ['花蓮', HUALIAN],
      ['宜蘭', YILAN]
    ]
  end

  class Output
    def initialize output_dir
      @extensions = {}
      Dir[File.join(output_dir, '*')].each{|file_path|
        extname = File.extname(file_path)[1..-1]
        @extensions[extname] ||= []
        @extensions[extname] << file_path
      }
    end

    def method_missing(method_id)
      str = method_id.id2name
      if @extensions[str]
        @extensions[str].size == 1 ? @extensions[str][0] : @extensions[str]
      else
        super
      end
    end
  end

  class SimulationJob < Struct.new(:simulation)
    def perform
      simulation.run
    end

    def success(job)
    end
  end
end

app/models/simulation/filter.rb
class Simulation::Filter
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_accessor :companies, :weathers, :building_models

  def initialize(attributes = {})
    attributes ||= {}
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def search_result
    sims = Simulation.scoped
    sims = sims.includes(:air_conditioner).where(products: {company: companies}) if companies.is_a?(Array) && companies.reject!(&:blank?).present?
    sims = sims.where weather: weathers if weathers.is_a?(Array) && weathers.reject!(&:blank?).present?
    sims = sims.where building_model: building_models if building_models.is_a?(Array) && building_models.reject!(&:blank?).present?
    sims
  end

  def persisted?
    false
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  is_admin               :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :confirmable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :simulations, uniq: true
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController
  before_filter :authenticate_user!, except: [:new]
  before_filter :set_sim, only: [:simulating, :show, :check]
  authorize_resource instance_name: :sim, except: [:new, :create]

  def index
    @filter = Simulation::Filter.new(params[:simulation_filter])
    @companies = Products::AirConditioner.select(:company).group(:company).map(&:company)
    @sims = @filter.search_result.accessible_by(current_ability).order('simulations.id DESC').page(params[:page])
  end

  def new
    @hit_count = HitCounter.increase
    @sim = Simulation.new
  end

  def create
    user = current_user || current_guest
    if @sim = user.simulations.create(params[:simulation])
      if same_sim = @sim.find_the_same
        @sim.update_attribute :simulation_dir, same_sim.simulation_dir
      else
        job = Simulation::SimulationJob.new(@sim)
        Delayed::Job.enqueue job
      end
      respond_to{|format|
        format.html{redirect_to simulating_simulation_path(@sim)}
        format.json{render json: {check_url: check_simulation_url(@sim)}}
      }
    else
    end
  end

  def simulating
    if @sim.simulation_dir
      redirect_to @sim
    end
  end

  def show
    if @sim.finished?
      begin
        @data = DataAnalysis.new @sim.output
        params[:no_layout] ? render(layout: nil) : render
      rescue
        Rails.logger.warn $!
        Rails.logger.debug $@.join($/)
        render file: @sim.output.html
      end
    else
      redirect_to simulating_simulation_path(@sim)
    end
  end

  def total_site_energy_compare
    @scale_override = (params[:start_value].present? && params[:end_value].present?).to_s
    @start_value = params[:start_value].presence && params[:start_value].to_i.abs
    @end_value = params[:start_value].presence && params[:end_value].to_i.abs
    @scale_steps = 10
    @scale_step_width = (@end_value.to_i - @start_value.to_i) / @scale_steps
    @scale_start_value = @start_value
    @simulations = Simulation.where(id: params[:simulation_ids]).select(&:finished?)
    @datas = DataAnalysis.retrieve_total_site_energies(@simulations)
  end

  # ajax
  def check
    render json: {sim: @sim, report_url: simulation_url(@sim)}
  end

  private
  def set_sim
    user = current_user || current_guest
    @sim = user.simulations.find_by_id(params[:id]) || user.simulations.last
    redirect_to root_path unless @sim
  end
end

app/helpers/simulation_helper.rb
module SimulationHelper
end

app/views/simulations/_air_conditioner_fields.html.haml
#for-normal
  .control-group
    = label_tag :air_conditioner_level, '能源分級', class: 'control-label'
    .controls
      = select_tag :air_conditioner_level, options_for_select(1..5)

  .control-group
    = label_tag :air_conditioner_cooling_capacity, '冷房能力 (kw)', class: 'control-label'
    .controls
      = select_tag :air_conditioner_cooling_capacity, options_for_select(%w(1~2 2~3 3~4))

  .control-group
    = label_tag :air_conditioner_type, '冷氣機種類', class: 'control-label'
    .controls
      = text_field_tag :air_conditioner_type, nil, placeholder: '忽略'

  .control-group
    = label_tag :air_conditioner, '冷氣機', class: 'control-label'
    .controls
      = text_field_tag :air_conditioner, nil, placeholder: '請輸入廠牌', style: 'width:300px'

#for-air
  .control-group
    = label_tag :air_conditioner_type_for_air, '冷氣機種類', class: 'control-label'
    .controls
      = select_tag :air_conditioner_type_for_air, options_for_select([['窗型冷氣(單體式)', 'single'],['分離式冷氣', 'separate'], ['箱型冷氣', 'box']])

  .control-group
    = label_tag :cooling_ability_for_air, '冷房能力（kW）', class: 'control-label'
    .controls
      = text_field_tag :cooling_ability_for_air

  .control-group
    = label_tag :energy_level_for_air, '能源效率', class: 'control-label'
    .controls
      = text_field_tag :energy_level_for_air

= f.association :air_conditioner, as: :hidden
= f.input :cop, label: '冷氣機效能 COP'
= f.input :rate_of_decline, label: '衰退率（%）', as: :integer, hint: '100 等於沒衰退', input_html: {min: 0, max: 100, value: 90}

app/views/simulations/_simulation.html.haml
%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th 建築類別
      %th 建築方位
      %th 室內空間
      %th 空間分配
      %th 地理位置
      %th 室內溫度設定
      %th 冷氣能源分級
      %th 冷氣機種類
      %th 冷氣機型號
      %th 冷氣機效能 COP
      %th 燈消耗功率
  %tbody
    %tr
      %td= simulation.building_model_text
      %td
        = simulation.deg
        度
      %td= simulation.room_space_text
      %td= simulation.room_space_ratial_text
      %td= simulation.weather_text
      %td= simulation.room_temperature
      %td= simulation.air_conditioner.try(:level)
      %td= simulation.air_conditioner.try(:air_conditioner_type)
      %td= simulation.air_conditioner.try(:registration_id)
      %td= simulation.cop
      %td= simulation.people

app/views/simulations/_step1.html.haml
%h2.StepTitle 選擇身份
%br
.btn-group{"data-toggle" => "buttons-radio"}
  = button_tag type: :button, id: 'role-normal-btn', class: 'btn btn-large btn-info active' do
    = image_tag 'user.png'
    %h2 一般使用者
  = button_tag type: :button, id: 'role-air-btn', class: 'btn btn-large btn-info' do
    = image_tag 'air.png'
    %h2 空調業者
  = button_tag type: :button, id: 'role-light-btn', class: 'btn btn-large btn-info' do
    = image_tag 'light.png'
    %h2 照明業者
  = button_tag type: :button, id: 'role-pro-btn', class: 'disabled btn btn-large btn-info' do
    = image_tag 'professor.png'
    %h2 建築專家
    %h1.coming-soon 建構中
= f.input :role, as: :hidden, input_html: {value: 'normal'}

app/views/simulations/_step2.html.haml
%h2.StepTitle 選擇建築模型
%br
%ul.nav.nav-pills
  %li.active= link_to '住宅類', '#living', 'data-toggle' => 'pill'
  %li= link_to '商業類', '#commercial', 'data-toggle' => 'pill'
.tab-content
  #living.tab-pane.active
    .btn-group{"data-toggle" => "buttons-radio"}
      = button_tag type: :button, id: '3f-btn', class: 'building-btn btn btn-large btn-success active', 'data-value' => '3f' do
        = image_tag '3F.jpg'
        %h2 三樓民宅
      = button_tag type: :button, id: '4f-btn', class: 'building-btn btn btn-large btn-success', 'data-value' => '4f' do
        = image_tag '4F.jpg'
        %h2 四樓民宅
      = button_tag type: :button, id: '10f-btn', class: 'building-btn btn btn-large btn-success' do
        = image_tag '10F.jpg'
        %h2 公寓大廈
        = select_tag :F10_select, options_for_select([['頂樓', 'top'], ['中間', 'mid'], ['一樓', 'btn']]), class: 'span1'
  #commercial.tab-pane
    .btn-group{"data-toggle" => "buttons-radio"}
      = button_tag type: :button, id: 'small-office-btn', class: 'btn btn-large btn-success active', 'data-value' => 'small_office' do
        = image_tag 'small-office-1.png'
        %h2 小型辦公室
= f.input :building_model, as: :hidden, input_html: {value: '3f'}

app/views/simulations/_step3.html.haml
%h2.StepTitle 選擇氣候
%br
%div= f.input_field :weather, collection: Simulation::Weather::OPTIONS, include_blank: false, label: false
%br
%embed#taiwan{src: asset_path('taiwan.svg'), type: 'image/svg+xml', height: 400}

app/views/simulations/_step4.html.haml
%h2.StepTitle 變數設定
= f.input :deg, label: '建築方位', as: :radio, collection: [['坐北朝南（0 度）', 0.0], ['坐東朝西（90 度）', 90], ['坐南朝北（180 度）', 180], ['坐西朝東（270 度）', 270], ['度', nil]], include_blank: false, checked: 0.0
= number_field_tag :deg_other, 0.0, step: :any, class: 'input-mini'
#air-vars
  = field_set_tag nil do
    = f.input :room_temperature, collection: (18..30).map{|i| ["#{i} 度 C", i]}, include_blank: false, label: '室內溫度', selected: 25
    = render 'air_conditioner_fields', f: f
#light-vars
  = field_set_tag nil do
    = f.input :power, collection: (5..15).map{|i| ["#{i} W/m^2", i]}, include_blank: false, label: '燈消耗功率'
    = f.input :sun_light, collection: (400..800).step(100), include_blank: '忽略', label: '日光照明'
  = field_set_tag do
    = f.input :people, collection: (2..6), label: '人數'
    = f.input :people_density, collection: (10.0..26.5).step(0.5).map{|float| ["#{float} 公尺平方/人（#{((155*3.3)/float).round} 人）", float]}, label: '室內人數（室內總人數）'

app/views/simulations/index.html.haml
= simple_form_for @filter, url: simulations_path, method: :get do |f|
  = f.input_field :companies, placeholder: '廠商', collection: @companies, multiple: true, class: 'select2'
  = f.input_field :weathers, collection: Simulation::Weather::OPTIONS, multiple: true, class: 'select2', placeholder: '氣候區'
  = f.input_field :building_models, collection: Simulation::BUILDING_MODEL_OPTIONS, multiple: true, class: 'select2', placeholder: '建築'
  = f.submit '搜尋', class: 'btn'
= form_tag total_site_energy_compare_simulations_path, method: :get do
  = submit_tag '比較', class: 'btn btn-primary'
  = paginate @sims
  %table.table
    %thead
      %th= check_box_tag :select_all
      %th #
      %th 冷氣機廠牌
      %th 冷氣機型號
      %th 建築類別
      %th 地理位置
      %th 狀態
      %th 時間
    %tbody
      - @sims.each do |sim|
        %tr
          %td= check_box_tag 'simulation_ids[]', sim.id, false, class: 'selectable'
          %td= link_to sim.id, sim
          %td= sim.air_conditioner.try(:company)
          %td= sim.air_conditioner.try(:name)
          %td= sim.building_model_text
          %td= sim.weather_text
          %td= content_tag(:span, sim.finished? ? '完成' : '尚未完成', class: "label #{sim.finished? ? 'label-success' : 'label-important'}")
          %td= l(sim.created_at, format: :long)
  = paginate @sims
  = submit_tag '比較', class: 'btn btn-primary'

app/views/simulations/new.html.haml
#wizard_container.row.hide
  .span12
    = simple_form_for @sim, html: {class: 'form-horizontal', :'data-type' => :json}, remote: true do |f|
      #wizard.swMain
        %ul
          %li
            %a{:href => "#step-1"}
              %label.stepNumber 1
              %span.stepDesc
                選擇身份
                %br/
                %small 選擇身份
          %li
            %a{:href => "#step-2"}
              %label.stepNumber 2
              %span.stepDesc
                選擇建築模型
                %br/
                %small 選擇建築模型
          %li
            %a{:href => "#step-3"}
              %label.stepNumber 3
              %span.stepDesc
                選擇氣候
                %br/
                %small 選擇氣候
          %li
            %a{:href => "#step-4"}
              %label.stepNumber 4
              %span.stepDesc
                變數設定
                %br/
                %small 變數設定
          %li
            %a{:href => "#step-5"}
              %label.stepNumber 5
              %span.stepDesc
                報表結果
                %br/
                %small 報表結果
        #step-1.step= render 'step1', f: f
        #step-2.step= render 'step2', f: f
        #step-3.step= render 'step3', f: f
        #step-4.step= render 'step4', f: f
        #step-5.step
          #report
          #simulating
            %h1
              模擬中
              %br
              %small 因不同案例與網路速度之差異，各分析案例所需時間不盡相同，平均需時 3~5 分鐘，請耐心等候……
            .progress.progress-striped.active
              .bar{:style => "width: 100%;"}
#splash_screen_container.row
  .offset4.span4= image_tag :'splash_screen.png', id: :splash_screen, class: 'hide'

app/views/simulations/simulating.html.haml
%h1
  模擬中
  %br
  %small 因不同案例與網路速度之差異，各分析案例所需時間不盡相同，平均需時 3~5 分鐘，請耐心等候……
.progress.progress-striped.active
  .bar{:style => "width: 100%;"}
:coffee
  setInterval () ->
    $.ajax
      url: '#{check_simulation_path(@sim)}',
      dataType: 'json'
    .done (data) ->
      console.log(data)
      window.location.replace('#{simulation_path(@sim)}') if data.sim.simulation_dir
  , 5000

app/views/simulations/total_site_energy_compare.html.haml
= form_tag total_site_energy_compare_simulations_path, method: :get do
  - params[:simulation_ids].each do |id|
    = hidden_field_tag :'simulation_ids[]', id
  = label_tag :start_value, '下邊界', style: 'display: inline'
  = number_field_tag :start_value, @start_value, class: 'input-mini', min: 0
  = label_tag :start_value, '上邊界', style: 'display: inline'
  = number_field_tag :end_value, @end_value, class: 'input-mini', min: 0
  = submit_tag '顯示', class: 'btn'
%canvas#chart{height: 512, width: @simulations.count*100, :'data-labels' => @simulations.map(&:id), :'data-data' => @datas, :'data-scale_override' => @scale_override, :'data-scale_steps' => @scale_steps, :'data-scale_step_width' => @scale_step_width, :'data-scale_start_value' => @scale_start_value}
%table.table
  %thead
    %tr
      %th 模擬編號
      %th 冷氣機廠牌
      %th 冷氣機型號
      %th 建築類別
      %th 總耗能（kWh）
  %tbody
    - @simulations.zip(@datas).each do |element|
      %tr
        %td= link_to element.first.id, element.first
        %td= element.first.air_conditioner.try(:company)
        %td= element.first.air_conditioner.try(:registration_id)
        %td= element.first.building_model_text
        %td= element.last
%br
= link_to '返回', simulations_path