config/routes.rb
WebEP::Application.routes.draw do
  devise_for :users

  resources :simulations, only: %i(index show new create) do
    member do
      get 'simulating'
      get 'check'
    end
    get 'total_site_energy_compare', on: :collection
  end

  scope controller: :home do
    get "index"
    get "help"
    get "comments"
  end

  resources :air_conditioners, as: :products_air_conditioners, controller: 'products', product_type: 'Products::AirConditioner'
  resources :lamps, as: :products_lamps, controller: 'products', product_type: 'Products::Lamp'

  resources :products do
    get 'search', on: :collection
    get 'attributes', on: :collection
  end

  root :to => 'simulations#new'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  level                :integer
#  product_type         :string(255)
#  company              :string(255)
#  cop                  :float
#  air_conditioner_type :string(255)
#  cooling_capacity     :float
#  registration_id      :string(255)
#

class Product < ActiveRecord::Base
  attr_accessible :name, :company, :level, :product_type, :registration_id

  validates :name, :level, :company, presence: true
  validates :level, inclusion: {in: (1..5)}
  PRODUCT_TYPES = %w(air_conditioner lamp)
  validates :product_type, presence: true, inclusion: PRODUCT_TYPES

  def self.search(params = {})
    products = Product.scoped
    products = products.where('company LIKE ?', "%#{params[:company]}%") if params[:company].present?
    %w(level product_type air_conditioner_type).each{|attribute|
      products = products.where(attribute => params[attribute]) if params[attribute].present?
    }
    if params['air_conditioner_cooling_capacity'].present?
      range = case params['air_conditioner_cooling_capacity']
              when "1~2" then (1.0...2.0)
              when "2~3" then (2.0...3.0)
              when "3~4" then (3.0...4.0)
              end
      products = products.where(cooling_capacity: range) if range
    end
    products
  end

  def lamp?
    product_type == 'lamp'
  end

  def air_conditioner?
    product_type == 'air_conditioner'
  end

  def downcast
    case product_type
    when 'air_conditioner' then becomes(Products::AirConditioner)
    when 'lamp' then becomes(Products::Lamp)
    else self
    end
  end

  def registration_year
    registration_id[/\w+-(\d+)-\d+/, 1]
  end
end

app/models/products.rb
module Products
  def self.table_name_prefix
    'products_'
  end
end

app/models/products/air_conditioner.rb
# == Schema Information
#
# Table name: products
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  level                :integer
#  product_type         :string(255)
#  company              :string(255)
#  cop                  :float
#  air_conditioner_type :string(255)
#  cooling_capacity     :float
#  registration_id      :string(255)
#

class Products::AirConditioner < Product
  attr_accessible :air_conditioner_type,
                  :cop, :cooling_capacity
  default_scope where(product_type: :air_conditioner)
  after_initialize{|x| x.product_type = 'air_conditioner'}

  has_many :simulations

  validates :product_type, inclusion: %w(air_conditioner)
  validates :cop, :cooling_capacity, :air_conditioner_type, presence: true
end

app/models/products/attribute.rb
class Products::Attribute < ActiveRecord::Base
  belongs_to :product
  attr_accessible :key, :value
  validates :key, :value, presence: true

  def self.search params = {}
    attributes = Products::Attribute.scoped.joins(:product)
    attributes = attributes.where('key LIKE ?', "%#{params[:term]}%") if params[:term].present?
    attributes = attributes.where('products.product_type' => params[:type]) if params[:type].present?
    attributes = attributes.group(:key)
    attributes = attributes.map{|x| {id: x.key, text: x.key}}
  end
end

app/models/products/lamp.rb
# == Schema Information
#
# Table name: products
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  level                :integer
#  product_type         :string(255)
#  company              :string(255)
#  cop                  :float
#  air_conditioner_type :string(255)
#  cooling_capacity     :float
#  registration_id      :string(255)
#

class Products::Lamp < Product
  default_scope where(product_type: :lamp)
  after_initialize{|x| x.product_type = 'lamp'}
  validates :product_type, inclusion: %w(lamp)
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'ej/ u06m04', except: %i(search attributes)
  before_filter :all_product, only: [:index]
  before_filter :new_product, only: [:new, :create]
  before_filter :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = model_class.where(id: params[:ids].split(',')) if params[:ids].present?
    respond_to do |format|
      format.html # index.html.erb
      format.json do
        # used in select2
        render json: @products.map{ |x| {id: x.id, text: x.name} }
      end
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: '新增成功' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: '更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    flash[:notice] = '已刪除'
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  # ajax for select2
  def search
    results = Product.search(params).page(params[:page]).per(10)
    results.map!{|x|
      {
        id: x.id,
        text: x.name,
        cop: '%.2f' % x.cop,
        company: x.company,
        air_conditioner_type: x.air_conditioner_type
      }
    } if [:select_options].present?
    render json: {
      results: results,
      more: params[:page].to_i < results.num_pages
    }
  end

  # ajax for select2
  def attributes
    attribute_name = params[:attribute]
    raise "attribute must be in #{Product.attribute_names}" unless Product.attribute_names.include?(attribute_name)
    results = Product.select(attribute_name).group(attribute_name)
    results = results.where("#{attribute_name} LIKE ?", "%#{params[:term]}%") if params[:term].present?
    results = results.page(params[:page]).per(10)
    results.map!{|x| {id: x.send(attribute_name), text: x.send(attribute_name)}}
    render json: {
      results: results,
      more: params[:page].to_i < results.num_pages
    }
  end

  private

  def model_class
    params[:product_type].blank? ? Product : params[:product_type].constantize
  end

  def all_product
    @products = model_class.page(params[:page]).per(10)
  end

  def new_product
    @product = model_class.new(params[:product])
  end

  def set_product
    @product = model_class.find(params[:id])
  end
end

app/helpers/products/lamps_helper.rb
module Products::LampsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_air_conditioner_fields.html.haml
- if @product.is_a? Products::AirConditioner
  = f.input :air_conditioner_type, input_html: {placeholder: '選擇類別'}
  = f.input :cop
  = f.input :cooling_capacity

app/views/products/_form.html.haml
= simple_nested_form_for(@product, as: :product) do |f|
  = f.error_notification
  .form-inputs
    .row
      .span4
        = f.input :name, input_html: {placeholder: '產品型號'}
        = f.input :company, input_html: {placeholder: '例：OOXX 股份有限公司'}
        = f.input :level, collection: (1..5), include_blank: false
        = f.input :registration_id, input_html: {placeholder: '例：AC-101-1387'}
        = render 'product_fields', f: f
        = render 'air_conditioner_fields', f: f
  .form-actions
    = f.button :submit

app/views/products/_product_fields.html.haml
- if @product.instance_of? Product
  = f.input :product_type, collection: Product::PRODUCT_TYPES.map{|x| [t(x, scope: :product_types), x]}, include_blank: false
- else
  = f.input :product_type, as: :hidden

app/views/products/edit.html.erb
<h1>編輯 <%= @product.name %></h1>

<%= render 'form' %>

<%= link_to '查看', @product %> |
<%= link_to '返回', products_path %>

app/views/products/index.html.haml
%h1 
  = t('.product_list')
  %small
    .btn-group
      = link_to '#', class: 'btn dropdown-toggle', 'data-toggle' => 'dropdown' do
        新增
        %span.caret
      %ul.dropdown-menu
        = nav_li Products::AirConditioner.model_name.human, new_products_air_conditioner_path
        = nav_li Products::Lamp.model_name.human, new_products_lamp_path
= paginate @products
.row
  .span6
    %table.table
      %thead
        %tr
          %th= Product.human_attribute_name :name
          %th= Product.human_attribute_name :company
          %th= Product.human_attribute_name :product_type
          %th 操作
      %tbody
        - @products.map(&:downcast).each do |product|
          %tr
            %td= product.name
            %td= product.company
            %td= t(product.product_type, scope: :product_types)
            %td
              = link_to product do
                %i.icon-link.icon-large.muted(title="查看")
              = link_to [:edit, product] do
                %i.icon-pencil.icon-large.muted(title="編輯")
              = link_to product, method: :delete, data: { confirm: '你確定？' } do
                %i.icon-trash.icon-large.muted(title="刪除")
= paginate @products

app/views/products/new.html.erb
<h1>新增 <%= @product.class.model_name.human %></h1>

<%= render 'form' %>

<%= link_to '返回', products_path %>

app/views/products/show.html.haml
%h1= @product.name
%dl
  %dt= Product.human_attribute_name :company
  %dd= @product.company
  %dt= Product.human_attribute_name :level
  %dd= @product.level
  %dt= Product.human_attribute_name :product_type
  %dd= t(@product.product_type, scope: :product_types)
  %dt= Product.human_attribute_name :registration_id
  %dd= @product.registration_id
  - if @product.air_conditioner?
    %dt= Product.human_attribute_name :air_conditioner_type
    %dd= t(@product.air_conditioner_type, scope: :air_conditioner_types)
    %dt= Product.human_attribute_name :cop
    %dd= @product.cop
    %dt= Product.human_attribute_name :cooling_capacity
    %dd= @product.cooling_capacity
-#.row
  .span2
    %table.table.table-bordered.table-striped.table-condensed.table-hover
      %thead
        %tr
          %th 變數名稱
          %th 值
      %tbody
        - @product.product_attributes.each do |attr|
          %tr
            %td= attr.key
            %td= attr.value

= link_to '編輯', [:edit, @product]
|
= link_to '返回', products_path
|
= link_to '刪除', @product, method: :delete, data: { confirm: '你確定？' }