config/routes.rb
WebEP::Application.routes.draw do
  devise_for :users

  resources :simulations, only: %i(index show new create) do
    member do
      get 'simulating'
      get 'check'
    end
    get 'total_site_energy_compare', on: :collection
  end

  scope controller: :home do
    get "index"
    get "help"
    get "comments"
  end

  resources :air_conditioners, as: :products_air_conditioners, controller: 'products', product_type: 'Products::AirConditioner'
  resources :lamps, as: :products_lamps, controller: 'products', product_type: 'Products::Lamp'

  resources :products do
    get 'search', on: :collection
    get 'attributes', on: :collection
  end

  root :to => 'simulations#new'

end

app/views/layouts/_footer.html.haml
%footer
  %p.pull-right
    %b= "建議使用 IE 8 以上或非 IE 瀏覽器（Chrome、Firefox、Opera）"
  %p
    &copy; #{image_tag 'itri.gif'} ITRI 2013
    |
    = link_to '聯絡我們', "mailto:lhw@itri.org.tw", target: :_blank
    |
    造訪次數：#{@hit_count}
    |
    資料來源：#{image_tag 'moeaboe.gif'} 經濟部能源局公告
    |
    模擬結果僅供參考

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to image_tag('LOGO+TEXT 128 X 325.png') + '1.1', root_path, id: 'logo', class: 'pull-left' %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <%= nav_li '說明', help_path %>
          <%= nav_li '意見交流', comments_path %>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <%= nav_li t('.admin'), products_path %>
                <%= nav_li '模擬紀錄', simulations_path %>
                <%= nav_li '編輯個人資料', edit_user_registration_path %>
                <%= nav_li t('.sign_out'), destroy_user_session_path, method: :delete %>
              </ul>
            </li>
          <% else %>
            <%= nav_li t('.sign_in'), new_user_session_path %>
          <% end %>
        </ul>
        <!--form class="navbar-form pull-right">
          <input class="span2" type="text" placeholder="Email">
          <input class="span2" type="password" placeholder="Password">
          <button type="submit" class="btn">Sign in</button>
        </form-->
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('site.name') %></title>
  <%= favicon_link_tag "LOGO 16 X 16.png" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!--[if lt IE 9]>
    <%= javascript_include_tag 'html5shiv' %>
    <%= javascript_include_tag 'excanvas' %>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>" data-controller="<%= controller_name %>" data-action="<%= action_name %>">
  <%= render :partial => 'layouts/navbar' %>
  <div class="container">
    <%= notice_message %>
    <%= yield %>
    <hr>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>